as_window = false
disable_click_to_close = false
force_keyboard_focus = false
monitor = ''
theme = 'catppuccin'
timeout = 0.0

[activation_mode]
use_alt = 'true'
labels = 'jkl;asdf'

[builtins]
[builtins.applications]
actions = true
context_aware = true
name = 'applications'
placeholder = 'Applications'
prioritize_new = true
refresh = true
show_generic = false
show_icon_when_single = true
show_sub_when_single = true
weight = 5.0

[builtins.calc]
icon = 'accessories-calculator'
min_chars = 4.0
name = 'calc'
placeholder = 'Calculator'
require_number = true
weight = 5.0

[builtins.clipboard]
avoid_line_breaks = true
exec = 'wl-copy'
image_height = 300.0
max_entries = 10.0
name = 'clipboard'
placeholder = 'Clipboard'
switcher_only = true
weight = 5.0

[builtins.commands]
icon = 'utilities-terminal'
name = 'commands'
placeholder = 'Commands'
switcher_only = true
weight = 5.0

[builtins.custom_commands]
icon = 'utilities-terminal'
name = 'custom_commands'
placeholder = 'Custom Commands'
weight = 5.0

[builtins.dmenu]
name = 'dmenu'
placeholder = 'Dmenu'
switcher_only = true
weight = 5.0

[builtins.emojis]
history = true
name = 'emojis'
placeholder = 'Emojis'
show_unqualified = false
switcher_only = true
typeahead = true
weight = 5.0

[builtins.finder]
concurrency = 8.0
icon = 'folder'
ignore_gitignore = true
name = 'finder'
placeholder = 'Finder'
refresh = true
switcher_only = true
weight = 5.0

[builtins.runner]
generic_entry = false
history = true
icon = 'utilities-terminal'
name = 'runner'
placeholder = 'Runner'
refresh = true
typeahead = true
weight = 5.0

[builtins.ssh]
history = true
icon = 'preferences-system-network'
name = 'ssh'
placeholder = 'SSH'
refresh = true
switcher_only = true
weight = 5.0

[builtins.switcher]
name = 'switcher'
placeholder = 'Switcher'
prefix = '/'
weight = 5.0

[builtins.websearch]
engines = ['duckduckgo', 'ecosia']
icon = 'applications-internet'
name = 'websearch'
placeholder = 'Websearch'
weight = 5.0

[builtins.windows]
icon = 'view-restore'
name = 'windows'
placeholder = 'Windows'
weight = 5.0

[list]
keyboard_scroll_style = 'emacs'
max_entries = 50.0
placeholder = 'No Results'
show_initial_entries = true
single_click = true
visibility_threshold = 20.0

[search]
delay = 0.0
placeholder = 'Search...'
