[pyprland]
plugins = ["scratchpads", "shortcuts_menu", "toggle_dpms"]

[scratchpads.notes]
animation = "fromBottom"
command = "kitty --class kitty-notes -d ~/notes --hold nvim ~/notes -c :WikiIndex"
# check: hyprctl clients | grep class
class = "kitty-notes"
size = "90% 90%"
margin = 50
lazy = "True"

[scratchpads.bt]
animation = "fromTop"
command = "kitty --class kitty-bt bluetuith"
class = "kitty-bt"
size = "50% 50%"
margin = 250
lazy = "True"

[scratchpads.sound]
animation = "fromTop"
command = "kitty --class kitty-sound pulsemixer"
class = "kitty-sound" 
size = "50% 50%"
margin = 250
lazy = "True"

[scratchpads.net]
animation = "fromTop"
command = "kitty --class kitty-net nmtui"
class = "kitty-net" 
size = "50% 50%"
margin = 250
lazy = "True"

[shortcuts_menu]
engine = "anyrun"
# parameters = "--prompt-text='[prompt]' --prompt-padding=0"
parameters = "--hide-plugin-info true --plugins libstdin.so --show-results-immediately true --max-entries 10"
submenu_end = ""

[shortcuts_menu.entries."󰣇 System"]
" Shutdown" = "systemctl poweroff"
"󰜉 Reboot" = "systemctl reboot"
" Lock" = "hyprlock"
"󰕾 Volume" = "pypr toggle sound"
"󰂯 Bluetooth" = "pypr toggle bt"
" Internet" = "pypr toggle net"
"󰶐 Screen Off" = "pypr toggle-dpms ; hyprctl dispatch submap screenoff"
"󰿅 Exit Hypr" = "hyprctl dispatch exit"
"󰒲 Suspend" = "systemctl suspend"

# [shortcuts_menu.entries."󰣇 System"."⏼ Power"]

